### ISSUE TITLE
Error if http:// is not specified on backend url

### ISSUE THREAD

**Issue by joeltgray** [saharmor/dalle-playground#40]
If http:// (or possibly https://) is not specified at the beginning of your backend url the following error is thrown: "Error querying DALL-E service. Check your backend server logs."

Not obvious to inexperienced users. #41

**Comment by saharmor** [comment]
That sounds strange, as the url validation happens before the query to the backend. I assume the issue is that you got a timeout after the backend took >1 min to generate your images--similar to this issue https://github.com/saharmor/dalle-playground/issues/67#issuecomment-1155979579.
Feel free to reopen and provide further details if you manage to reproduce.
