### ISSUE TITLE
DALL-E server doesn't work with AMD GPU

### ISSUE THREAD

**Issue by joeltgray** [saharmor/dalle-playground#49]
Running on Ubuntu 20.4 LTS native, with AMD RX 6600 XT GPU. Local development - no docker

GPU works with OpenGL as I can run glmark2 and Blender using OpenGL and my GPU, but can't seem to run with DALL-E server.

`$ python3 app.py 8080
--> Starting DALL-E Server. This might take up to two minutes.
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
Aborted (core dumped)`

Any help would be great!

**Comment by Codel1417** [comment]
This requires cuda which is only available on NVidia GPUs

**Comment by joeltgray** [comment]
Any plans to support AMD GPUs?

**Comment by osimmac** [comment]
> This requires cuda which is only available on NVidia GPUs

I believe it requires Pytorch, which has experimental support for AMD gpus via ROCm : https://pytorch.org/get-started/locally/
when installing pytorch through pip3, you can verify pytorch can use the gpu by:
`python3
>>>import pytorch
>>>torch.cuda.is_available()
true`

with my 6900xt, i was able to get pytorch to recognize my gpu. however i can't get this app to recognize it, i also get the same error:
`$ python3 app.py 20000
--> Starting DALL-E Server. This might take up to two minutes.
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
`

any info would be appreciated. im on LTS ubuntu 20.04,4,  on the 5.13.0-48-generic kernel. 

general hw info:
ryzen7 5800x
32gb ram
6900xt
also have gtx 1060 because maybe ROCm is only available/ intended for headless setups so thought maybe i could use the nvidia gpu for video and the amd gpu just for compute.

**Comment by NevesLucas** [comment]
I have it working on a 6800xt without issues

rocm works fine on full desktop, no need for headless. Using rocm 5.1.0 works correctly, need to build jaxlib from source with the  `--enable_rocm` flag, and also specifying the path to the correct rocm install with `--rocm_path=/opt/rocm-5.1.0` .

after that, the regular install process for dalle works fine, just ensure it doesnt attempt to install a non-rocm jaxlib over your build!

Should note i had to make sure the jax repository was checked out to the latest tagged commit (jax-v0.3.13 at time of writing), just cloning the repo doesnt work correctly.

**Comment by DarkShadow44** [comment]
FWIW, I don't think this project uses pytorch at all, not sure why it says it does.
I compiled jaxlib for rocm, but I get the following error:
`2022-06-29 04:45:34.924212: I external/org_tensorflow/tensorflow/compiler/xla/service/platform_util.cc:145] StreamExecutor ROCM device (0) is of unsupported AMDGPU version : gfx1010. The supported AMDGPU versions are gfx1030, gfx900, gfx906, gfx908, gfx90a.`

I edited tensorflow/jaxlib to allow my GPU here: https://gist.github.com/DarkShadow44/60decf1ae76cd1143479620193b53ebe

Now I get ```ImportError: /usr/lib/python3.10/site-packages/jaxlib/xla_extension.so: undefined symbol: _ZN10tensorflow33tensor_float_32_execution_enabledEv```

Not sure if that's because of my unsupported GPU or because I compiled it wrong somehow?

**Comment by NevesLucas** [comment]
@DarkShadow44 do you have an rx5700xt? You might need to do a full clean of the bazel cache if you previously tried building with the wrong device flags. Where in the original source tree is the files you edited?

**Comment by NevesLucas** [comment]
@exander77 hi sorry I never put it in a docker environment, I did a native install to my Linux system

**Comment by joeltgray** [comment]
Closing as @NevesLucas seems to have provided a working solution, and thread has gone stale.

Thanks to everyone for their input!
