### ISSUE TITLE
Mega model does not work at all

### ISSUE THREAD

**Issue by Gushousekai195** [saharmor/dalle-playground#71]
I have a Colab Pro subscription and everything. Whenever I try to use the Mega model, it results in “Error querying DALL-E service. Check your backend server logs.”

But the server logs say that it generated images just fine. Where are the images?!

**Comment by trekkie1701c** [comment]
If you generate too many images (in my experience, more than 2) the localtunnel thingy will time out.

What I've found best on Colab is to enable some form of disk saving and then to just use that, with the web interface being more to issue commands and maybe preview the images.  If you link a Google Drive account, you can also modify a copy of the Notebook to save everything there automatically so that you don't have to worry about it being deleted when the runtime is terminated.

**Comment by saharmor** [comment]
I have a Google Colab Pro+ and I can generate five images before the one-minute timeout. 
+1 on @trekkie1701c's suggestion of saving to disk by passing the `--save_to_disk` flag, e.g.
`python3 app.py --port 8000 --model_version mega --save_to_disk true`

**Comment by saharmor** [comment]
Closing this for now but feel free to reopen if it's a different issue than the timeout one.
